### ISSUE TITLE
iOS - ListView inside of Popup no longer firing ItemSelected unless list item is long pressed 

### ISSUE THREAD

**Issue by iupchris10** [rotorgames/Rg.Plugins.Popup#8]
I am using a Popup with a ListView and custom ViewCell inside. This was working just fine in version 0.0.9, but since upgrading to 0.0.12 I now have to press the listview item for a few seconds and release in order for ItemSelected to fire. I used to only need to tap the list item quickly.

Again, this worked fine in 0.0.9. Not sure what changed since then. The XAML in my PCL looks like this....

```
<pages:PopupPage xmlns="http://xamarin.com/schemas/2014/forms" xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml" 
xmlns:pages="clr-namespace:Rg.Plugins.Popup.Pages;assembly=Rg.Plugins.Popup">

<ListView x:Name="ListView" ItemSelected="OnSelection" >
		<ListView.ItemTemplate>
			<DataTemplate>
					<ViewCell>
				             <StackLayout Orientation="Horizontal" >
						<Label Text = "{Binding DisplayValue}" ></Label>
					     </StackLayout>
					</ViewCell>
			</DataTemplate>
		</ListView.ItemTemplate>
</ListView>

</pages:PopupPage>

```

**Comment by rotorgames** [comment]
@iupchris10 Hey. This error occurs only on Android or ios?

**Comment by iupchris10** [comment]
iOS - sorry I forgot to mention.

**Comment by iupchris10** [comment]
I'm also using Xamarin Forms. The XAML code I listed above is from my Portable Class Library project.

**Comment by rotorgames** [comment]
@iupchris10 Please, please, Xamarin.Forms version, Xamarin.IOS and IOS SDK

**Comment by iupchris10** [comment]
Xamarin.Forms 2.1.0.6529
Xaramin.iOS 9.4.1.25
iOS SDK 9.2

**Comment by rotorgames** [comment]
@iupchris10 Yes, I can confirm this bug. This is due to the implementation of gestures PopupPageRenderer for ios. Once corrected, I will inform you. Thank you.

**Comment by rotorgames** [comment]
@iupchris10 I fixed this bug. As soon as will Nuget version 0.0.13, upgrade to it.

Write to me after the test the. Thank you.

**Comment by iupchris10** [comment]
Just upgraded to 0.0.13 and so far everything is working. I'll keep an eye on it. Thank you so much for addressing so quickly!

**Comment by rotorgames** [comment]
Happy to help.

**Comment by Amenti** [comment]
I believe this bug is back again in 1.0.4. Tested with Forms 2.3.4.

**Comment by rotorgames** [comment]
@Amenti Try to use 1.1.0-pre2

**Comment by Amenti** [comment]
@rotorgames  Tried it out. Sorry, it's the same behaviour.

**Comment by Amenti** [comment]
@rotorgames Sorry to have bothered you. The problem is in fact not Rg.Plugins.Popup but the different handling of GestureRecognizers in iOS and Android. When multiple GestureRecognizers are registered iOS seems to favor the last one and Android calls them all. This led to the problem in my case.

**Comment by dfarrNTST** [comment]
Amenti/rotorgames - We are hitting this issue...how do we get around it?  The popup is receiving the tap and not the ListView/SelectedItem.

**Comment by rotorgames** [comment]
@dfarrNTST Can you show your xaml?
